### PR TITLE
date of birth checks

### PR DESCRIPTION
**Pull request by Mugisha-Beline**

### CODE REVIEW

**Comment by Freedisch** [comment]
Hey, you should escape a forward slash with a back slash like that [ \ / ], add a forward slash to your back slash before I merge it

**Comment by Mugisha-Beline** [comment]
So you mean I need to add back slash and a forward slash?

**Comment by Freedisch** [comment]
Yes, that's it \ /

**Comment by Freedisch** [comment]
Cool, everything looks good now.

**Review by Freedisch — APPROVED** [review]
Regex code validation works ✅

**Pull request merged**
